//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportwebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class College_Name
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public College_Name()
        {
            this.Department_Table = new HashSet<Department_Table>();
        }
    
        public decimal College_ID { get; set; }
        public string College_Name1 { get; set; }
    
        public virtual College_Address College_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department_Table> Department_Table { get; set; }
    }
}
