//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reportwebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department_Table()
        {
            this.Course_Table = new HashSet<Course_Table>();
            this.Instructor_Table = new HashSet<Instructor_Table>();
        }
    
        public decimal Department_ID { get; set; }
        public decimal College_ID { get; set; }
        public string Department_Name { get; set; }
        public decimal Course_Year { get; set; }
    
        public virtual College_Name College_Name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Table> Course_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructor_Table> Instructor_Table { get; set; }
    }
}
