//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment_Course
    {
        public decimal Assignemt_ID { get; set; }
        public string Course_Number { get; set; }
        public decimal ID_Number { get; set; }
        public decimal Period_ID { get; set; }
        public decimal No_of_Students { get; set; }
    
        public virtual Assignment_Name Assignment_Name { get; set; }
        public virtual Course_Table Course_Table { get; set; }
    }
}
