//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classroom_table()
        {
            this.Course_Table = new HashSet<Course_Table>();
        }
    
        public decimal Class_Number { get; set; }
        public decimal Building_ID { get; set; }
        public decimal Capacity_ID { get; set; }
        public decimal Class_Status { get; set; }
        public decimal Features_ID { get; set; }
        public decimal Capacity_status { get; set; }
    
        public virtual Building_Table Building_Table { get; set; }
        public virtual Capacity_OK Capacity_OK { get; set; }
        public virtual Classroom_Capacity Classroom_Capacity { get; set; }
        public virtual Classroom_Features Classroom_Features { get; set; }
        public virtual Classroom_Free Classroom_Free { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Table> Course_Table { get; set; }
    }
}
