//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Table()
        {
            this.Assignment_Course = new HashSet<Assignment_Course>();
            this.Classroom_table = new HashSet<Classroom_table>();
            this.Period_Table = new HashSet<Period_Table>();
            this.Student_Table = new HashSet<Student_Table>();
        }
    
        public string Course_Number { get; set; }
        public string Course_Name { get; set; }
        public decimal College_ID { get; set; }
        public decimal Department_ID { get; set; }
        public decimal ID_Number { get; set; }
        public decimal Pre_ID { get; set; }
        public decimal No_of_Students { get; set; }
        public string Course_Assigned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment_Course> Assignment_Course { get; set; }
        public virtual Course_Prerequisites Course_Prerequisites { get; set; }
        public virtual Department_Table Department_Table { get; set; }
        public virtual Instructor_Table Instructor_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Classroom_table> Classroom_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Period_Table> Period_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Table> Student_Table { get; set; }
    }
}
