//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseTimetable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Course_TimetableEntities : DbContext
    {
        public Course_TimetableEntities()
            : base("name=Course_TimetableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment_Course> Assignment_Course { get; set; }
        public virtual DbSet<Assignment_Name> Assignment_Name { get; set; }
        public virtual DbSet<Building_Table> Building_Table { get; set; }
        public virtual DbSet<Capacity_OK> Capacity_OK { get; set; }
        public virtual DbSet<Classroom_Capacity> Classroom_Capacity { get; set; }
        public virtual DbSet<Classroom_Features> Classroom_Features { get; set; }
        public virtual DbSet<Classroom_Free> Classroom_Free { get; set; }
        public virtual DbSet<Classroom_table> Classroom_table { get; set; }
        public virtual DbSet<College_Address> College_Address { get; set; }
        public virtual DbSet<College_Name> College_Name { get; set; }
        public virtual DbSet<Course_Prerequisites> Course_Prerequisites { get; set; }
        public virtual DbSet<Course_Table> Course_Table { get; set; }
        public virtual DbSet<Department_Table> Department_Table { get; set; }
        public virtual DbSet<Instructor_Table> Instructor_Table { get; set; }
        public virtual DbSet<Period_Free> Period_Free { get; set; }
        public virtual DbSet<Period_Table> Period_Table { get; set; }
        public virtual DbSet<Semester_Table> Semester_Table { get; set; }
        public virtual DbSet<Student_Grade> Student_Grade { get; set; }
        public virtual DbSet<Student_Table> Student_Table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
