//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Table()
        {
            this.Course_Table = new HashSet<Course_Table>();
        }
    
        public decimal Student_ID { get; set; }
        public string First_name { get; set; }
        public string initial { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public decimal Grade_ID { get; set; }
    
        public virtual Student_Grade Student_Grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course_Table> Course_Table { get; set; }
    }
}
